services:
  yva-app:
    image: yva:latest
    container_name: yva-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - AUTH_MODE=${AUTH_MODE:-development}
      - ALLOW_MODE_SWITCHING=${ALLOW_MODE_SWITCHING:-true}
      - SESSION_DURATION_DAYS=${SESSION_DURATION_DAYS:-90}
      - API_KEY=${API_KEY}
    env_file:
      - ${ENV_FILE:-.env.development}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/api/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 3s
      start_period: 40s
      retries: 3
